[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
logic = { path = "../../logic" }

[dependencies.uuid]
version = "1.10.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]
